### ISSUE TITLE
Check installability of `depends` before starting the build process

### ISSUE THREAD

**Issue by vigress8** [pacstall/pacstall#1114]
### Is your feature related to a problem? Please describe.

`depends` are blindly attempted to be installed and only after the pacscript has been packaged, which if they are not installable for any reason fails and results in a lot of wasted time

### A clear and concise description of what you want to happen.

Check `depends` for installability before doing anything, and fail immediately if any problems are found

**Comment by oklopfer** [comment]
The reason why they're only installed after the package has been created is because they're called by the .deb itself to be installed, not by an apt command. that being said, we already do this kind of check for optdeps: https://github.com/pacstall/pacstall/blob/0aa34d904f404859d505e78b7f4edd0caca0d130/misc/scripts/build.sh#L107-L118

**Comment by oklopfer** [comment]
implemented after a series of PRs

**Comment by vigress8** [comment]
I suggest documenting the series of PRs here
