### ISSUE TITLE
pacstall Debian package has wrong dependency name

### ISSUE THREAD

**Issue by UriHerrera** [pacstall/pacstall#19]
**Describe the bug**
The Debian package in the Releases tab lists the following dependencies: `Depends: curl, wget, unzip, build-essentials`  However, one of the dependencies is wrong.

The package `build-essentials` does not exist in Debian nor Ubuntu; the correct name is `build-essential` without the _s_.

**To Reproduce**
1. Download the Debian package from the Releases tab.
2. Try to install it.
3. The package fails to install because it's missing the dependency.

**Expected behavior**
The package is installed.

**Screenshots**

![VirtualBox_Nitrux (legacy)_25_05_2021_19_29_25](https://user-images.githubusercontent.com/3053525/119585106-a0c26700-bd8f-11eb-8ebc-811288da631d.png)

![VirtualBox_Nitrux (legacy)_25_05_2021_19_31_02](https://user-images.githubusercontent.com/3053525/119585216-d9fad700-bd8f-11eb-8d76-0908c45e6a9a.png)

**Desktop (please complete the following information):**

- OS + version: Nitrux 1.4.0.
- Pacstall Version: 1.2

**Comment by wizard-28** [comment]
Three things...
1. I believe that the `.deb` file dependency issue will be fixed in the next release.
2. It's not recommended to install pacstall though the `.deb` package from the releases tab, as the releases can be quite old (1 week old max), the recommended way to install pacstall is [in this section ](https://github.com/pacstall/pacstall#installing)of the readme file (This has the dependency and other problems fixed)
3. Pacstall only officially supports Ubuntu based distros, though you can try to use it in other distros with varied success.

**Comment by Henryws** [comment]
Could you try to install using this command: `sudo bash -c "$(curl -fsSL https://git.io/JsADh || wget -q https://git.io/JsADh -O -)"`

**Comment by wizard-28** [comment]
> Could you try to install using this command: `sudo bash -c "$(curl -fsSL https://git.io/JsADh || wget -q https://git.io/JsADh -O -)"`

@Henryws Looks like @UriHerrera is packaging pacstall in Nitrux OS, so I don't think using this command will help with his case, as apt repositories require `.deb` files

**Comment by Henryws** [comment]
It should work as all he needs are a couple packages then the rest is just wgeting stuff

**Comment by Henryws** [comment]
Also looking [https://github.com/Henryws/pacstall-tools/blob/7fffe6860f3d09079b4c07fe63c456796acfc094/pacstall-deb#L16](url), it shows that it is trying to put `build-essentials` into the deb

**Comment by Henryws** [comment]
Fixed it, re download the latest release
