### ISSUE TITLE
pacstall develop version keeps changing /usr/src/pacstall owner to pacstall running account.

### ISSUE THREAD

**Issue by kwon37xi** [pacstall/pacstall#242]
**Describe the bug**
* After installing a package, pacstall changes the owner of `/usr/src/pacstall` and subdirectories of the directory to pacstall runner account.

**To Reproduce**
* just before installing a package
```
$ ls -lah
drwxr-xr-x  8 kwon37xi kwon37xi 4.0K  9월  6 23:52 .
drwxr-xr-x 15 root     root     4.0K  9월  3 08:53 ..
drwxr-xr-x  4 kwon37xi kwon37xi 4.0K  9월  6 00:16 aws-cli-v2-bin
drwxr-xr-x  3 kwon37xi kwon37xi 4.0K  8월 25 20:36 exa
drwxr-xr-x  3 kwon37xi kwon37xi 4.0K  9월  3 09:35 grive2
drwxr-xr-x  3 kwon37xi kwon37xi 4.0K  9월  6 23:44 nerd-fonts-inconsolata
drwxr-xr-x  3 kwon37xi kwon37xi 4.0K  9월  6 01:35 universal-ctags-git
drwxr-xr-x  3 root     root     4.0K  9월  6 23:52 youtube-dl-git   <------- root 
```

* after install a package
```
$ pacstall -I zotero

$ ls -lah
drwxr-xr-x  9 kwon37xi kwon37xi 4.0K  9월  6 23:57 .
drwxr-xr-x 15 root     root     4.0K  9월  3 08:53 ..
drwxr-xr-x  4 kwon37xi kwon37xi 4.0K  9월  6 00:16 aws-cli-v2-bin
drwxr-xr-x  3 kwon37xi kwon37xi 4.0K  8월 25 20:36 exa
drwxr-xr-x  3 kwon37xi kwon37xi 4.0K  9월  3 09:35 grive2
drwxr-xr-x  3 kwon37xi kwon37xi 4.0K  9월  6 23:44 nerd-fonts-inconsolata
drwxr-xr-x  3 kwon37xi kwon37xi 4.0K  9월  6 01:35 universal-ctags-git
drwxr-xr-x  3 kwon37xi kwon37xi 4.0K  9월  6 23:52 youtube-dl-git       <---- owner changed to kwon37xi
drwxr-xr-x  4 root     root     4.0K  9월  6 23:57 zotero <--- owner is root
```
**Expected behavior**
* `/usr/src/pacstall` and it's subdirectories owner and group must be `root:root`.

**Desktop (please complete the following information):**

- OS + version: Ubuntu 21.04
- Pacstall Version + branch: 1.6 development

**Comment by wizard-28** [comment]
It's kind of not really a bug, since we implemented `fakeroot`, we need `STOWDIR` to be owned by the user. Otherwise they (the maintainers) would have to use `sudo` to move stuff there.

---

I don't exactly know why `zotero`'s owned by root after installation. Everything should be owned by the user I guess. Summoning @Henryws for clarification.

I've one theory as to why that's happening. Probably because the `zotero` `pacscript` uses `sudo install` to move stuff there inturn making the directory owned by `root`. Not sure though.

**Comment by Henryws** [comment]
> I've one theory as to why that's happening. Probably because the zotero pacscript uses sudo install to move stuff there inturn making the directory owned by root. Not sure though.

Seems like the logical conclusion. I have no idea why other scripts are changing permissions though

**Comment by wizard-28** [comment]
> Seems like the logical conclusion. I have no idea why other scripts are changing permissions though

The other scripts (folders) changing owners (ex: `youtube-dl-git`) is the expected behavior. It's probably caused by this line.
https://github.com/pacstall/pacstall/blob/e9928fea7b75f184c9845c4a5e6e1cbf0f2ed828/misc/scripts/install-local.sh#L443

Now that I think about it, I don't think it'll work as currently it's before `install` function so it doesn't really affect the package folder (not yet created). In turn not affecting the script.

So it won't be possible to use `install` without `sudo` in the script.

**Comment by Henryws** [comment]
so maybe we could put that line before and after `install`?

**Comment by wizard-28** [comment]
I don't exactly know, what's happening as I said. So it's hard to pin point at which point the owners change. We'll probably find out when testing the 1.6 branch

**Comment by wizard-28** [comment]
Let this issue stay open till it's resolved.

**Comment by kwon37xi** [comment]
I thought `/usr/*` should be owned by `root`.
If `/usr/src/pacstall/*` is owned by a specific user, what will happen when there are many users in one system.
For example, `bob` installed a package, but `alice` want to upgrade the package, what will happen??

**Comment by Henryws** [comment]
> I thought `/usr/*` should be owned by `root` and pacscript packagers treat `/usr/src/pacstall/*`  as `root`'s area.
> If `/usr/src/pacstall/*` is owned by a specific user, what will happen when there are many users in one system.
> For example, `bob` installed a package(so, `/usr/src/pacstall/somepackage` is owned by `bob`), but `alice` want to upgrade the package, what will happen??
> 

Apt installs globably too. If Bob has packages installed by apt, and Alice upgrades, Bob has a new version as well as Alice

**Comment by kwon37xi** [comment]
Yes, I mean apt installs files as `root`, but pacstall does not. Will it ok when `/usr/src/pacstall/somepackage` is not owned by `root`??

**Comment by NarutoXY** [comment]
No it's not OK. Instead what we should do is to take an approach like AUR and Home Manager. To put all the `/usr/src/pacstall` stuff in `~/.cache/pacstall` and `~/.local/share/pacstall`. In this way we can sorta reduce the complexities on a multi user system, by compiling in home dir and moving the binary to `/usr/bin/foo` as root.
