### ISSUE TITLE
You seem to be offline

### ISSUE THREAD

**Issue by NillyTheL0L** [pacstall/pacstall#516]
**Describe the bug**

-->
1. I think the script dont detect my wifi

**Screenshots**
[Screen](https://user-images.githubusercontent.com/97253814/157555549-ef3f29cd-6ea1-41bc-a055-8b3d339e1654.png)

**Desktop (please complete the following information):**

- Voyager 20.04 (based on Xubuntu 20.04)
- 1.7.2

**Comment by D-Brox** [comment]
This is an issue with your DNS provider. It happens for me too.

The ping tests are unable to ping github.com due to a redirect problem. You can edit `/usr/bin/pacstall` and replace all instances of `ping -c 1 github.com` with `ping -c 1 1.1.1.1` to fix this error.

This issue is being fixed in the next bug fix release, IIRC.

**Comment by Henryws** [comment]
@NillyTheL0L run `pacstall -U pacstall develop` to get the fix.

**Comment by NillyTheL0L** [comment]
> @NillyTheL0L run `pacstall -U pacstall develop` to get the fix.

Tysm

**Comment by D-Brox** [comment]
You can also update to the develop branch with `pacstall -U pacstall develop`, which currently has some other bug fixes too
