### ISSUE TITLE
Package source directory not cleaned during upgrade

### ISSUE THREAD

**Issue by raxod502** [pacstall/pacstall#536]
### Describe the bug

The contents of `/usr/src/pacstall/$name` are not removed before a new version of a package is installed, which has a number of adverse effects, e.g.:

* Arbitrary artifacts may be left from previous versions of the package, with unknown effects.
* Maintainers may update a Pacscript in an incorrect way and not realize the error since the installation operates differently on a new machine versus an existing one. I suspect this is what introduced the bug I fixed in https://github.com/pacstall/pacstall-programs/pull/893.

### To reproduce

To reproduce, create a file inside `/usr/src/pacstall/$name`, where `$name` is any package you have installed. Then, upgrade the package and observe that the file has not been removed.

### Expected behavior

All files should be removed from `/usr/src/pacstall/$name` before the new version is installed. The result of installing a package on a new system should always be identical to upgrading it from a previous version on an existing system.

For the sake of not breaking an existing installation, files should be installed into a temporary directory, which should then be moved into place in a final step. Note: this problem will mostly go away when Pacstall migrates fully to installing packages in Debian format rather than relying on Stow, but it will still be necessary to build packages in a separate directory from where they are eventually installed.

### Screenshots

![image](https://user-images.githubusercontent.com/6559064/160526913-15dcb11c-7ce4-44a8-b583-4db52be4306b.png)

### OS version

Pop!_OS 21.10

### Pacstall version

https://github.com/pacstall/pacstall/commit/1b09ad194bf6187cdc5465171e34c0a2487071e7

**Comment by wizard-28** [comment]
We've been experimenting with many ways on how to deal with this problem, but none of them are feasible, or even possible to do. Here's what we've tried:

* move the old package directory while expecting symlinks won't break, so that we can unstow the old directory and stow the new one. This won't work because symlinks will break if you try to move them.
* change `$STOWDIR` to a temporary directory, install everything there, the remove the actual `STOWDIR`, then move the temporary one, then stow, however this won't work with a lot of scripts calling symlinks.
* the only feasible option is to unstow the old package and then install the new one, however, this would incur a noticeable downtime, especially for source based packages (-git).

Fixing this would incur breaking changes, so we'll address this in 2.0.0 where we switch from the current stow based installation system to a deb based one.

**Comment by Henryws** [comment]
We have moved to Debian packagine.
