### ISSUE TITLE
Allow downloading of a file from package directory

### ISSUE THREAD

**Issue by sarmong** [pacstall/pacstall#574]
### Is your feature related to a problem? Please describe.

I am trying to make a nerd-fonts package. The install script there installs it in the user data location, but it needs to be installed into `/usr`
For that, [AUR script](https://aur.archlinux.org/packages/nerd-fonts-complete) applies a patch to the install script.

First, it downloads `fix-installer-font-dir.patch` from the same location the package build script is located in and then applies it.

```
source=(
  'fix-installer-font-dir.patch'
  "${_gitname}-${pkgver}.tar.gz::https://github.com/ryanoasis/nerd-fonts/archive/v${pkgver}.tar.gz"
)
```

### A clear and concise description of what you want to happen.

1. Possibility to specify multiple files in `url` field.
2. Possibility to add custom files to package folder and download them.

**Comment by wizard-28** [comment]
Yeah it's already possible to download files from our repository.

See https://github.com/pacstall/pacstall-programs/blob/e33ed155dfaa0bdcffd1823df4f8cb665ad103a4/packages/amfora-bin/amfora-bin.pacscript,
 https://github.com/pacstall/pacstall-programs/blob/f9521b29ed3fce0a25f9727aa063201cb40eef70/packages/spacecadetpinball-git/spacecadetpinball-git.pacscript,
 https://github.com/pacstall/pacstall-programs/blob/b61a39330206b520567a95b4712fe29543332be4/packages/endlessh-git/endlessh-git.pacscript


You basically add whatever you want to download to the same package in the repository, then download it from there.

---

For version 2.0.0. we'll be switching to a superset of the PKGBUILD format, so that would include all the features PKGBUILDs have (like `source` array), plus some pacstall specific features on top.

**Comment by sarmong** [comment]
Looking forward to 2.0!

As I understand, now I can only download from the URL, right? Meaning, I will not be able to test this locally

**Comment by D-Brox** [comment]
Currently, only the url and patches
